apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    app: {{ .Values.serviceAccount.labels.app | camelcase }}
    tier: {{ .Values.serviceAccount.labels.tier | title }}
