apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    {{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  selector:
    name: webapp-color
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}